import type { CourseSlug } from "./material-paths.ts";
import { normalizeMaterialPath, normalizeSegment } from "./material-paths.ts";

export const ALLOWED_UPLOADS: Record<string, readonly string[]> = { ".html": ["text/html"], ".pdf": ["application/pdf"], ".doc": ["application/msword"], ".docx": ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"], ".ppt": ["application/vnd.ms-powerpoint"], ".pptx": ["application/vnd.openxmlformats-officedocument.presentationml.presentation"], ".odt": ["application/vnd.oasis.opendocument.text"], ".odp": ["application/vnd.oasis.opendocument.presentation"], ".jpg": ["image/jpeg"], ".jpeg": ["image/jpeg"], ".png": ["image/png"], ".gif": ["image/gif"], ".webp": ["image/webp"], ".svg": ["image/svg+xml"], ".mp3": ["audio/mpeg"], ".wav": ["audio/wav"], ".m4a": ["audio/mp4"], ".mp4": ["video/mp4"], ".webm": ["video/webm"], ".mov": ["video/quicktime"], ".zip": ["application/zip", "application/x-zip-compressed"] };
export const FOLDER_MARKER = "folder";
export const isCourse = (value: string): value is CourseSlug => value === "finanzas" || value === "finanzas-corporativas";
export function materialKey(course: CourseSlug, folder: string, file: string): string { return `materiales/${course}/${normalizeMaterialPath(folder)}/${normalizeSegment(file)}`; }
export function validateUpload(pathname: string, contentType: string): string[] { const match = /^materiales\/(finanzas|finanzas-corporativas)\/(.+)\/([^/]+)$/.exec(pathname); if (!match || match[3] === ".folder") throw new Error("Ruta de carga inválida"); const safe = materialKey(match[1] as CourseSlug, match[2], match[3]); if (safe !== pathname) throw new Error("Ruta de carga inválida"); const extension = `.${match[3].split(".").at(-1)?.toLowerCase()}`; const allowed = ALLOWED_UPLOADS[extension]; if (!allowed || (!allowed.includes(contentType) && contentType !== "application/octet-stream")) throw new Error("Tipo de archivo no permitido"); return [...allowed, "application/octet-stream"]; }
export function validateMaterialPath(path: string): string { if (!path.startsWith("materiales/")) throw new Error("Ruta inválida"); const normalized = normalizeMaterialPath(path.slice("materiales/".length)); const [course, ...rest] = normalized.split("/"); if (!isCourse(course) || !rest.length) throw new Error("Ruta inválida"); return `materiales/${normalized}`; }
